### ISSUE TITLE
variables in regex

### ISSUE THREAD

**Issue by carloschavez9** [mbfrankz/LyricsReloaded#7]
I was trying to use variables in the regex for darklyrics (the name of the song is needed) with no success. Is it really possible to use these variables in that regex? or is there code change needed?

The variable I need is the title of the song.

```
name: DarkLyrics

variables:
    artist:
        type: artist
        filters:
        - lowercase
        - strip_nonascii
    title:
        type: title
        filters:
        - lowercase
    album:
        type: album
        filters: artist

headers:
    User-Agent: 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:30.0) Gecko/20100101 Firefox/30.0' # Firefox 30 Win x64 user agent

config:
    url: "http://www.darklyrics.com/lyrics/{artist}/{album}.html"
    pattern: ['<h3><a name(.+){title}(.?)<\\/a><\\/h3><br \\/>(?<lyrics>.+?)<h3>', si]
    
post-filters:
- strip_html
- trim
- utf8_encode
```
